#[derive(Copy, Clone, Debug)]
pub struct Span {
    pub start: u32,
    pub end: u32,
}

#[derive(Copy, Clone, Debug)]
pub struct Token {
    pub span: Span,
    pub kind: TokenKind,
}

#[derive(Copy, Clone, PartialEq, Debug)]
pub enum TokenKind {
    Ident,
    // Literals
    LitNull,
    LitBool(bool),
    LitInt(u64),
    LitFloat(f64),
    LitString,
    // Special
    Error,
    Eof,
    // Keywords
    KwPub,
    KwMod,
    KwMut,
    KwSelf,
    KwImpl,
    KwEnum,
    KwStruct,
    KwImport,
    // Stmt
    KwIf,
    KwElse,
    KwFor,
    KwDefer,
    KwBreak,
    KwReturn,
    KwContinue,
    // Expr
    KwCast,
    KwSizeof,
    // Type
    KwBool,
    KwS8,
    KwS16,
    KwS32,
    KwS64,
    KwSsize,
    KwU8,
    KwU16,
    KwU32,
    KwU64,
    KwUsize,
    KwF32,
    KwF64,
    KwChar,
    // Delimeter
    OpenParen,
    OpenBlock,
    OpenBracket,
    CloseParen,
    CloseBlock,
    CloseBracket,
    // Separator
    At,
    Dot,
    Colon,
    Comma,
    Semicolon,
    DotDot,
    ColonColon,
    ArrowThin,
    ArrowWide,
    /// Unary op
    LogicNot,
    BitNot,
    // Binary cmp
    LogicAnd,
    LogicOr,
    Less,
    Greater,
    LessEq,
    GreaterEq,
    IsEq,
    NotEq,
    // Binary op
    Plus,
    Minus,
    Times,
    Div,
    Mod,
    BitAnd,
    BitOr,
    BitXor,
    Shl,
    Shr,
    // Assign op
    Assign,
    PlusEq,
    MinusEq,
    TimesEq,
    DivEq,
    ModEq,
    BitAndEq,
    BitOrEq,
    BitXorEq,
    ShlEq,
    ShrEq,
}

impl Token {
    pub fn new(start: u32, end: u32, kind: TokenKind) -> Self {
        Self {
            span: Span { start, end },
            kind,
        }
    }

    pub fn eof() -> Self {
        Self::new(0, 0, TokenKind::Eof)
    }
}

impl TokenKind {
    pub fn as_str(&self) -> &'static str {
        match self {
            TokenKind::Ident => "ident",
            TokenKind::LitNull => "null",
            TokenKind::LitBool(..) => "bool literal",
            TokenKind::LitInt(..) => "integer literal",
            TokenKind::LitFloat(..) => "float literal",
            TokenKind::LitString => "string literal",
            TokenKind::Error => "error token",
            TokenKind::Eof => "end of file token",
            TokenKind::KwPub => "pub",
            TokenKind::KwMod => "mod",
            TokenKind::KwMut => "mut",
            TokenKind::KwSelf => "self",
            TokenKind::KwImpl => "impl",
            TokenKind::KwEnum => "enum",
            TokenKind::KwStruct => "struct",
            TokenKind::KwImport => "import",
            TokenKind::KwIf => "if",
            TokenKind::KwElse => "else",
            TokenKind::KwFor => "for",
            TokenKind::KwDefer => "defer",
            TokenKind::KwBreak => "break",
            TokenKind::KwReturn => "return",
            TokenKind::KwContinue => "continue",
            TokenKind::KwCast => "cast",
            TokenKind::KwSizeof => "sizeof",
            TokenKind::KwBool => "bool",
            TokenKind::KwS8 => "s8",
            TokenKind::KwS16 => "s16",
            TokenKind::KwS32 => "s32",
            TokenKind::KwS64 => "s64",
            TokenKind::KwSsize => "ssize",
            TokenKind::KwU8 => "u8",
            TokenKind::KwU16 => "u16",
            TokenKind::KwU32 => "u32",
            TokenKind::KwU64 => "u64",
            TokenKind::KwUsize => "usize",
            TokenKind::KwF32 => "f32",
            TokenKind::KwF64 => "f64",
            TokenKind::KwChar => "char",
            TokenKind::OpenParen => "(",
            TokenKind::OpenBlock => "{",
            TokenKind::OpenBracket => "[",
            TokenKind::CloseParen => ")",
            TokenKind::CloseBlock => "}",
            TokenKind::CloseBracket => "]",
            TokenKind::At => "@",
            TokenKind::Dot => ".",
            TokenKind::Colon => ":",
            TokenKind::Comma => ",",
            TokenKind::Semicolon => ";",
            TokenKind::DotDot => "..",
            TokenKind::ColonColon => "::",
            TokenKind::ArrowThin => "->",
            TokenKind::ArrowWide => "=>",
            TokenKind::LogicNot => "!",
            TokenKind::BitNot => "~",
            TokenKind::LogicAnd => "&&",
            TokenKind::LogicOr => "||",
            TokenKind::Less => "<",
            TokenKind::Greater => ">",
            TokenKind::LessEq => "<=",
            TokenKind::GreaterEq => ">=",
            TokenKind::IsEq => "==",
            TokenKind::NotEq => "!=",
            TokenKind::Plus => "+",
            TokenKind::Minus => "-",
            TokenKind::Times => "*",
            TokenKind::Div => "/",
            TokenKind::Mod => "%",
            TokenKind::BitAnd => "&",
            TokenKind::BitOr => "|",
            TokenKind::BitXor => "^",
            TokenKind::Shl => "<<",
            TokenKind::Shr => ">>",
            TokenKind::Assign => "=",
            TokenKind::PlusEq => "+=",
            TokenKind::MinusEq => "-=",
            TokenKind::TimesEq => "*=",
            TokenKind::DivEq => "/=",
            TokenKind::ModEq => "%=",
            TokenKind::BitAndEq => "&=",
            TokenKind::BitOrEq => "|=",
            TokenKind::BitXorEq => "^=",
            TokenKind::ShlEq => "<<=",
            TokenKind::ShrEq => ">>=",
        }
    }
}
